import { Hook, Connection, Encapsulation } from '../store';
/**
 * Hook where the render will be generated by its keyName
 * @param keyName keyName to identify by render
 * @param index its additional
*/
export declare type UseRender = (keyName: string, index?: number | string) => void;
export default function createUseRender(registers: Map<string, Hook | Connection | Encapsulation>): UseRender;
