import { Hook, Connection, Encapsulation } from '../store';
export interface UseRender {
    /**
     * Hook where the render will be generated by its keyName
     * @param keyName keyName to identify by render
     * @param index its additional
    */
    (keyName?: string, index?: number | string): () => void;
}
export default function createUseRender(registers: Map<string, Hook | Connection | Encapsulation>): UseRender;
